/*
 * NanoXLSX is a small .NET library to generate and read XLSX (Microsoft Excel 2007 or newer) files in an easy and native way  
 * Copyright Raphael Stoeckli © 2025
 * This library is licensed under the MIT License.
 * You find a copy of the license in project folder or on: http://opensource.org/licenses/MIT
 */

using NanoXLSX.Interfaces.Writer;
using NanoXLSX.Registry;
using NanoXLSX.Registry.Attributes;
using NanoXLSX.Utils.Xml;

namespace NanoXLSX.Internal.Writers
{
    /// <summary>
    /// Class to generate the metadata XML file for the app metadata part on an XLSX file.
    /// </summary>
    [NanoXlsxPlugIn(PlugInUUID = PlugInUUID.METADATA_APP_WRITER)]
    internal class MetadataAppWriter : IPlugInWriter
    {
        private XmlElement properties;

        #region properties
        /// <summary>
        /// Gets or replaces the workbook instance, defined by the constructor
        /// </summary>
        public Workbook Workbook { get; set; }

        /// <summary>
        /// Gets the main XML element, generated by <see cref="Execute"/>
        /// </summary>
        public XmlElement XmlElement { get => properties; }

        #endregion
        #region constructors
        /// <summary>
        /// Default constructor - Must be defined for instantiation of the plug-ins
        /// </summary>
        internal MetadataAppWriter()
        {
        }

        #endregion
        #region methods
        /// <summary>
        /// Initialization method (interface implementation)
        /// </summary>
        /// <param name="baseWriter">Base writer instance that holds any information for this writer</param>
        public void Init(IBaseWriter baseWriter)
        {
            this.Workbook = baseWriter.Workbook;
        }

        /// <summary>
        /// Method to execute the main logic of the plug-in (interface implementation)
        /// </summary>
        public void Execute()
        {
            properties = XmlElement.CreateElement("Properties");
            properties.AddDefaultXmlNameSpace("http://schemas.openxmlformats.org/officeDocument/2006/extended-properties");
            properties.AddNameSpaceAttribute("vt", "xmlns", "http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes");
            Metadata md = Workbook.WorkbookMetadata;
            properties.AddChildElementWithValue("TotalTime", "0");
            properties.AddChildElementWithValue("Application", md.Application);
            properties.AddChildElementWithValue("DocSecurity", "0");
            properties.AddChildElementWithValue("ScaleCrop", "false");
            properties.AddChildElementWithValue("Manager", md.Manager);
            properties.AddChildElementWithValue("Company", md.Company);
            properties.AddChildElementWithValue("LinksUpToDate", "false");
            properties.AddChildElementWithValue("SharedDoc", "false");
            properties.AddChildElementWithValue("HyperlinkBase", md.HyperlinkBase);
            properties.AddChildElementWithValue("HyperlinksChanged", "false");
            properties.AddChildElementWithValue("AppVersion", md.ApplicationVersion);

            WriterPlugInHandler.HandleInlineQueuePlugins(ref properties, Workbook, PlugInUUID.METADATA_APP_INLINE_WRITER);
        }

        #endregion
    }
}
