/*
 * NanoXLSX is a small .NET library to generate and read XLSX (Microsoft Excel 2007 or newer) files in an easy and native way  
 * Copyright Raphael Stoeckli © 2025
 * This library is licensed under the MIT License.
 * You find a copy of the license in project folder or on: http://opensource.org/licenses/MIT
 */

using NanoXLSX.Colors;
using NanoXLSX.Exceptions;
using NanoXLSX.Interfaces;
using NanoXLSX.Interfaces.Writer;
using NanoXLSX.Registry;
using NanoXLSX.Registry.Attributes;
using NanoXLSX.Styles;
using NanoXLSX.Utils;
using NanoXLSX.Utils.Xml;
using System.Collections.Generic;
using System.Linq;
using static NanoXLSX.Styles.Border;
using static NanoXLSX.Styles.CellXf;
using static NanoXLSX.Styles.Fill;
using static NanoXLSX.Styles.Font;
using static NanoXLSX.Styles.NumberFormat;

namespace NanoXLSX.Internal.Writers
{
    /// <summary>
    /// Class to generate the style XML file in a XLSX file.
    /// </summary>
    [NanoXlsxPlugIn(PlugInUUID = PlugInUUID.StyleWriter)]
    internal class StyleWriter : IPlugInWriter
    {

        private StyleManager styles;
        private XmlElement styleSheet;
        private IColorWriter colorWriter;

        #region properties
        /// <summary>
        /// Gets or replaces the workbook instance, defined by the constructor
        /// </summary>
        public Workbook Workbook { get; set; }

        /// <summary>
        /// Gets the main XML element, generated by <see cref="Execute"/>
        /// </summary>
        public XmlElement XmlElement { get => styleSheet; }

        #endregion
        #region constructors
        /// <summary>
        /// Default constructor - Must be defined for instantiation of the plug-ins
        /// </summary>
        internal StyleWriter()
        {
        }

        #endregion
        #region methods
        /// <summary>
        /// Initialization method (interface implementation)
        /// </summary>
        /// <param name="baseWriter">Base writer instance that holds any information for this writer</param>
        public void Init(IBaseWriter baseWriter)
        {
            this.styles = baseWriter.Styles;
            this.Workbook = baseWriter.Workbook;
            this.colorWriter = PlugInLoader.GetPlugIn<IColorWriter>(PlugInUUID.ColorWriter, new ColorWriter());
        }

        /// <summary>
        /// Method to execute the main logic of the plug-in (interface implementation)
        /// </summary>
        public void Execute()
        {
            styleSheet = XmlElement.CreateElement("styleSheet");
            styleSheet.AddDefaultXmlNameSpace("http://schemas.openxmlformats.org/spreadsheetml/2006/main");
            styleSheet.AddNameSpaceAttribute("mc", "xmlns", "http://schemas.openxmlformats.org/markup-compatibility/2006");
            styleSheet.AddNameSpaceAttribute("x14ac", "xmlns", "http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac");
            styleSheet.AddAttribute("mc:Ignorable", "x14ac");
            int numFormatCount = styles.GetNumberFormatStyleNumber();
            int fontCount = styles.GetFontStyleNumber();
            int fillCount = styles.GetFillStyleNumber();
            int borderCount = styles.GetBorderStyleNumber();
            int styleCount = styles.GetStyleNumber();
            if (numFormatCount > 0)
            {
                XmlElement numFmts = XmlElement.CreateElementWithAttribute("numFmts", "count", ParserUtils.ToString(numFormatCount));
                numFmts.AddChildElements(GetNumberFormatElements());
                styleSheet.AddChildElement(numFmts);
            }
            XmlElement fonts = XmlElement.CreateElementWithAttribute("fonts", "count", ParserUtils.ToString(fontCount));
            fonts.AddAttribute("knownFonts", "1", "x14ac");
            fonts.AddChildElements(GetFontElements());
            styleSheet.AddChildElement(fonts);
            XmlElement fills = XmlElement.CreateElementWithAttribute("fills", "count", ParserUtils.ToString(fillCount));
            fills.AddChildElements(GetFillElements());
            styleSheet.AddChildElement(fills);
            XmlElement borders = XmlElement.CreateElementWithAttribute("borders", "count", ParserUtils.ToString(borderCount));
            borders.AddChildElements(GetBorderElements());
            styleSheet.AddChildElement(borders);
            XmlElement cellXfs = XmlElement.CreateElementWithAttribute("cellXfs", "count", ParserUtils.ToString(styleCount));
            cellXfs.AddChildElements(GetCellXfElements());
            styleSheet.AddChildElement(cellXfs);
            if (Workbook.WorkbookMetadata != null)
            {
                XmlElement mruElement = GetMruElement();
                if (mruElement != null)
                {
                    XmlElement colors = styleSheet.AddChildElement("colors");
                    colors.AddChildElement(mruElement);
                }
            }

            WriterPlugInHandler.HandleInlineQueuePlugins(ref styleSheet, Workbook, PlugInUUID.StyleInlineWriter);
        }

        /// <summary>
        /// Method to get all border elements of the style
        /// </summary>
        /// <returns>List of border elements</returns>
        private List<XmlElement> GetBorderElements()
        {
            Border[] borderStyles = styles.GetBorders();
            List<XmlElement> borders = new List<XmlElement>(borderStyles.Length);
            foreach (Border item in borderStyles)
            {
                XmlElement border = XmlElement.CreateElement("border");
                if (item.DiagonalDown && !item.DiagonalUp) { border.AddAttribute("diagonalDown", "1"); }
                else if (!item.DiagonalDown && item.DiagonalUp) { border.AddAttribute("diagonalUp", "1"); }
                else if (item.DiagonalDown && item.DiagonalUp)
                {
                    border.AddAttribute("diagonalDown", "1");
                    border.AddAttribute("diagonalUp", "1");
                }
                if (item.LeftStyle != StyleValue.None)
                {
                    XmlElement left = border.AddChildElementWithAttribute("left", "style", Border.GetStyleName(item.LeftStyle));
                    if (!string.IsNullOrEmpty(item.LeftColor)) { left.AddChildElementWithAttribute("color", "rgb", item.LeftColor); }
                    else { left.AddChildElementWithAttribute("color", "auto", "1"); }
                }
                else
                {
                    border.AddChildElement("left");
                }
                if (item.RightStyle != StyleValue.None)
                {
                    XmlElement right = border.AddChildElementWithAttribute("right", "style", Border.GetStyleName(item.RightStyle));
                    if (!string.IsNullOrEmpty(item.RightColor)) { right.AddChildElementWithAttribute("color", "rgb", item.RightColor); }
                    else { right.AddChildElementWithAttribute("color", "auto", "1"); }
                }
                else
                {
                    border.AddChildElement("right");
                }
                if (item.TopStyle != StyleValue.None)
                {
                    XmlElement top = border.AddChildElementWithAttribute("top", "style", Border.GetStyleName(item.TopStyle));
                    if (!string.IsNullOrEmpty(item.TopColor)) { top.AddChildElementWithAttribute("color", "rgb", item.TopColor); }
                    else { top.AddChildElementWithAttribute("color", "auto", "1"); }
                }
                else
                {
                    border.AddChildElement("top");
                }
                if (item.BottomStyle != StyleValue.None)
                {
                    XmlElement bottom = border.AddChildElementWithAttribute("bottom", "style", Border.GetStyleName(item.BottomStyle));
                    if (!string.IsNullOrEmpty(item.BottomColor)) { bottom.AddChildElementWithAttribute("color", "rgb", item.BottomColor); }
                    else { bottom.AddChildElementWithAttribute("color", "auto", "1"); }
                }
                else
                {
                    border.AddChildElement("bottom");
                }
                if (item.DiagonalStyle != StyleValue.None)
                {
                    XmlElement diagonal = border.AddChildElementWithAttribute("diagonal", "style", Border.GetStyleName(item.DiagonalStyle));
                    if (!string.IsNullOrEmpty(item.DiagonalColor)) { diagonal.AddChildElementWithAttribute("color", "rgb", item.DiagonalColor); }
                    else { diagonal.AddChildElementWithAttribute("color", "auto", "1"); }
                }
                else
                {
                    border.AddChildElement("diagonal");
                }
                borders.Add(border);
            }
            return borders;
        }

        /// <summary>
        /// Method to get all font elements of the style
        /// </summary>
        /// <returns>List of font elements</returns>
        private List<XmlElement> GetFontElements()
        {
            Font[] fontStyles = styles.GetFonts();
            List<XmlElement> fonts = new List<XmlElement>(fontStyles.Length);
            foreach (Font item in fontStyles)
            {
                XmlElement font = XmlElement.CreateElement("font");
                if (item.Bold) { font.AddChildElement("b"); }
                if (item.Italic) { font.AddChildElement("i"); }
                if (item.Strike) { font.AddChildElement("strike"); }
                if (item.Underline != UnderlineValue.None && item.Underline != UnderlineValue.Single)
                {
                    font.AddChildElementWithAttribute("u", "val", Font.GetUnderlineName(item.Underline));
                }
                else if (item.Underline == UnderlineValue.Single)
                {
                    font.AddChildElement("u");
                }
                if (item.VerticalAlign != VerticalTextAlignValue.None)
                {
                    font.AddChildElementWithAttribute("vertAlign", "val", Font.GetVerticalTextAlignName(item.VerticalAlign));
                }
                font.AddChildElementWithAttribute("sz", "val", ParserUtils.ToString(item.Size));
                if (string.IsNullOrEmpty(item.ColorValue))
                {
                    font.AddChildElementWithAttribute("color", "theme", ParserUtils.ToString((int)item.ColorTheme));
                }
                else
                {
                    font.AddChildElementWithAttribute("color", "rgb", item.ColorValue);
                }
                font.AddChildElementWithAttribute("name", "val", item.Name);
                font.AddChildElementWithAttribute("family", "val", ParserUtils.ToString((int)item.Family));
                if (item.Scheme != SchemeValue.None)
                {
                    if (item.Scheme == SchemeValue.Major)
                    { font.AddChildElementWithAttribute("scheme", "val", "major"); }
                    else if (item.Scheme == SchemeValue.Minor)
                    { font.AddChildElementWithAttribute("scheme", "val", "minor"); }
                }
                font.AddChildElementWithAttribute("charset", "val", ParserUtils.ToString((int)item.Charset));
                fonts.Add(font);
            }
            return fonts;
        }

        /// <summary>
        /// Method to get all fill elements of the style
        /// </summary>
        /// <returns>List of fill elements</returns>
        private List<XmlElement> GetFillElements()
        {
            Fill[] fillStyles = styles.GetFills();
            List<XmlElement> fills = new List<XmlElement>(fillStyles.Length);
            foreach (Fill fill in fillStyles)
            {
                XmlElement fillElement = XmlElement.CreateElement("fill");
                XmlElement patternFillElement = fillElement.AddChildElement("patternFill");
                patternFillElement.AddAttribute("patternType", Fill.GetPatternName(fill.PatternFill));
                if (fill.PatternFill == PatternValue.Solid)
                {
                    // For solid fills: fgColor contains the actual fill color
                    XmlElement foregroundColor = XmlElement.CreateElement("fgColor");
                    foregroundColor.AddAttributes(colorWriter.GetAttributes(fill.ForegroundColor));

                    // bgColor with indexed="64" is standard for solid fills when using RGB/theme colors
                    if (fill.BackgroundColor.IsDefined)
                    {
                        XmlElement backgroundColor = XmlElement.CreateElement("bgColor");
                        backgroundColor.AddAttributes(colorWriter.GetAttributes(fill.BackgroundColor));
                        patternFillElement.AddChildElement(backgroundColor);
                    }
                    else if (fill.ForegroundColor.Type == Color.ColorType.Rgb ||
                             fill.ForegroundColor.Type == Color.ColorType.Theme)
                    {
                        // Add default indexed="64" for solid fills with RGB or theme colors
                        XmlElement backgroundColor = XmlElement.CreateElement("bgColor");
                        Color indexedColor = Color.CreateIndexed(IndexedColor.DefaultIndexedColor);
                        backgroundColor.AddAttributes(colorWriter.GetAttributes(indexedColor));
                        patternFillElement.AddChildElement(backgroundColor);

                    }
                    patternFillElement.AddChildElement(foregroundColor);
                }
                else if (fill.PatternFill != PatternValue.None)
                {
                    XmlElement fgColor = XmlElement.CreateElement("fgColor");
                    fgColor.AddAttributes(colorWriter.GetAttributes(fill.ForegroundColor));
                    patternFillElement.AddChildElement(fgColor);
                    XmlElement bgColor = XmlElement.CreateElement("bgColor");
                    bgColor.AddAttributes(colorWriter.GetAttributes(fill.BackgroundColor));
                    patternFillElement.AddChildElement(bgColor);
                }
                fills.Add(fillElement);
            }
            return fills;
        }

        /// <summary>
        /// Method to get all numberFormat elements of the style
        /// </summary>
        /// <returns>List of numberFormat elements</returns>
        private List<XmlElement> GetNumberFormatElements()
        {
            NumberFormat[] numberFormatStyles = styles.GetNumberFormats();
            List<XmlElement> elements = new List<XmlElement>(numberFormatStyles.Length);
            foreach (NumberFormat item in numberFormatStyles)
            {
                if (item.IsCustomFormat)
                {
                    if (string.IsNullOrEmpty(item.CustomFormatCode))
                    {
                        throw new FormatException("The number format style component with the ID " + ParserUtils.ToString(item.CustomFormatID) + " cannot be null or empty");
                    }
                    // OOXML: Escaping according to Chp.18.8.31
                    // TODO: v3> Add a custom format builder
                    XmlElement element = XmlElement.CreateElementWithAttribute("numFmt", "formatCode", XmlUtils.SanitizeXmlValue(item.CustomFormatCode));
                    element.AddAttribute("numFmtId", ParserUtils.ToString(item.CustomFormatID));
                    elements.Add(element);
                }
            }
            return elements;
        }

        /// <summary>
        /// Method to get all cellXf elements of the style
        /// </summary>
        /// <returns>List of cellXf elements</returns>
        private List<XmlElement> GetCellXfElements()
        {
            Style[] styleItems = this.styles.GetStyles();
            List<XmlElement> xfs = new List<XmlElement>(styleItems.Length);
            foreach (Style style in styleItems)
            {
                int textRotation = style.CurrentCellXf.CalculateInternalRotation();
                XmlElement alignment = null;
                XmlElement protection = null;
                if (style.CurrentCellXf.HorizontalAlign != HorizontalAlignValue.None || style.CurrentCellXf.VerticalAlign != VerticalAlignValue.None || style.CurrentCellXf.Alignment != TextBreakValue.None || textRotation != 0)
                {
                    alignment = XmlElement.CreateElement("alignment");
                    if (style.CurrentCellXf.HorizontalAlign != HorizontalAlignValue.None)
                    {
                        string alignValue = CellXf.GetHorizontalAlignName(style.CurrentCellXf.HorizontalAlign);
                        alignment.AddAttribute("horizontal", alignValue);
                    }
                    if (style.CurrentCellXf.VerticalAlign != VerticalAlignValue.None)
                    {
                        string alignValue = CellXf.GetVerticalAlignName(style.CurrentCellXf.VerticalAlign);
                        alignment.AddAttribute("vertical", alignValue);
                    }
                    if (style.CurrentCellXf.Indent > 0 &&
                        (style.CurrentCellXf.HorizontalAlign == HorizontalAlignValue.Left
                        || style.CurrentCellXf.HorizontalAlign == HorizontalAlignValue.Right
                        || style.CurrentCellXf.HorizontalAlign == HorizontalAlignValue.Distributed))
                    {
                        alignment.AddAttribute("indent", ParserUtils.ToString(style.CurrentCellXf.Indent));
                    }
                    if (style.CurrentCellXf.Alignment != TextBreakValue.None)
                    {
                        if (style.CurrentCellXf.Alignment == TextBreakValue.ShrinkToFit) { alignment.AddAttribute("shrinkToFit", "1"); }
                        else { alignment.AddAttribute("wrapText", "1"); }
                    }
                    if (textRotation != 0)
                    {
                        alignment.AddAttribute("textRotation", ParserUtils.ToString(textRotation));
                    }
                }
                if (!style.CurrentCellXf.Locked || style.CurrentCellXf.Hidden)
                {
                    protection = XmlElement.CreateElement("protection");
                    if (style.CurrentCellXf.Hidden && style.CurrentCellXf.Locked)
                    {
                        protection.AddAttribute("hidden", "1"); // Locked is true by default (no need to define)
                    }
                    else if (style.CurrentCellXf.Hidden && !style.CurrentCellXf.Locked)
                    {
                        protection.AddAttribute("hidden", "1");
                        protection.AddAttribute("locked", "0");
                    }
                    else if (!style.CurrentCellXf.Hidden && !style.CurrentCellXf.Locked)
                    {
                        protection.AddAttribute("locked", "0"); // To be defined, since locked is true by default (no need for hidden, since false by default)

                    }
                }
                else
                {
                    protection = null; // No definition if only locked == true
                }
                XmlElement xf = XmlElement.CreateElement("xf");
                if (style.CurrentNumberFormat.IsCustomFormat)
                {
                    xf.AddAttribute("numFmtId", ParserUtils.ToString(style.CurrentNumberFormat.CustomFormatID));
                }
                else
                {
                    int formatNumber = (int)style.CurrentNumberFormat.Number;
                    xf.AddAttribute("numFmtId", ParserUtils.ToString(formatNumber));
                }
                xf.AddAttribute("borderId", ParserUtils.ToString(style.CurrentBorder.InternalID.Value));
                xf.AddAttribute("fillId", ParserUtils.ToString(style.CurrentFill.InternalID.Value));
                xf.AddAttribute("fontId", ParserUtils.ToString(style.CurrentFont.InternalID.Value));
                if (!style.CurrentFont.IsDefaultFont)
                {
                    xf.AddAttribute("applyFont", "1");
                }
                if (style.CurrentFill.PatternFill != PatternValue.None)
                {
                    xf.AddAttribute("applyFill", "1");
                }
                if (!style.CurrentBorder.IsEmpty())
                {
                    xf.AddAttribute("applyBorder", "1");
                }
                if (alignment != null || style.CurrentCellXf.ForceApplyAlignment)
                {
                    xf.AddAttribute("applyAlignment", "1");
                }
                if (protection != null)
                {
                    xf.AddAttribute("applyProtection", "1");
                }
                if (style.CurrentNumberFormat.Number != FormatNumber.None)
                {
                    xf.AddAttribute("applyNumberFormat", "1");
                }
                if (alignment != null || protection != null)
                {
                    xf.AddChildElement(alignment);
                    xf.AddChildElement(protection);
                }
                xfs.Add(xf);
            }
            return xfs;
        }

        /// <summary>
        /// Method to get the Color MRU element of the style
        /// </summary>
        /// <returns>XmlElement, holding Color MRU information</returns>
        private XmlElement GetMruElement()
        {
            XmlElement mruColors = null;
            List<SrgbColor> tempColors = new List<SrgbColor>();
            foreach (Color color in Workbook.GetMruColors())
            {
                if (!color.IsDefined || (color.Type != Color.ColorType.Rgb && color.Type != Color.ColorType.Indexed))
                {
                    continue;
                }
                SrgbColor tempColor = null;
                if (color.Type == Color.ColorType.Rgb)
                {
                    tempColor = color.RgbColor;
                }
                else // Indexed
                {
                    tempColor = color.IndexedColor.GetSrgbColor();
                }
                if (tempColor.StringValue == SrgbColor.DefaultSrgbColor)
                {
                    continue;
                }
                if (!tempColors.Any(c => c.StringValue == tempColor.StringValue))
                {
                    tempColors.Add(tempColor);
                }
            }
            if (tempColors.Count > 0)
            {
                mruColors = XmlElement.CreateElement("mruColors");
                foreach (SrgbColor item in tempColors)
                {
                    mruColors.AddChildElementWithAttribute("color", "rgb", item.ColorValue);
                }
            }
            return mruColors;
        }
        #endregion
    }
}
