/*
 * NanoXLSX is a small .NET library to generate and read XLSX (Microsoft Excel 2007 or newer) files in an easy and native way
 * Copyright Raphael Stoeckli © 2026
 * This library is licensed under the MIT License.
 * You find a copy of the license in project folder or on: http://opensource.org/licenses/MIT
 */

using System.Collections.Generic;
using NanoXLSX.Utils.Xml;

namespace NanoXLSX.Interfaces.Writer
{
    /// <summary>
    /// Interface, used by classes to register package parts prior, and to write package parts at the end of the XLSX creation process 
    /// </summary>
    /// \remark <remarks>All List&lt;T&gt; entries must contain the <b>same number of elements</b>, otherwise exceptions may be thrown on <see cref="IPlugin.Execute"/></remarks>
    internal interface IPluginPackageWriter : IPluginWriter
    {
        /// <summary>
        /// List of order numbers of the package parts (for sorting purpose during registration)
        /// </summary>
        List<int> OrderNumbers { get; }

        /// <summary>
        /// Current index that should be used in <see cref="IPlugin.Execute"/>, to identify the current action to execute.
        /// The index will automatically be set during the iterative execution of the plug-in, from 0 to the count (-1) of the defined List&lt;T&gt; elements
        /// </summary>
        int CurrentIndex { get; set; }
        /// <summary>
        /// List of relative paths of the package parts
        /// </summary>
        List<string> PackagePartPaths { get; }
        /// <summary>
        /// List of the file names of the package parts
        /// </summary>
        List<string> PackagePartFileNames { get; }
        /// <summary>
        /// List of the content types of the target file of the parts (usually kind of XML)
        /// </summary>
        List<string> ContentTypes { get; }
        /// <summary>
        /// List of the schema URLs of the target file of the parts (usually kind of XML schema)
        /// </summary>
        List<string> RelationshipTypes { get; }
        /// <summary>
        /// List of location statement. If true, the package part is in the root directory, otherwise in the 'xl' sub-directory (with various sub-sub-directories)
        /// </summary>
        List<bool> ArePackagePartsRoot { get; }

        /// <summary>
        /// Gets the List of main XML elements, that is generated by <see cref="IPlugin.Execute"/>. In this interface, <see cref="IPluginWriter.XmlElement"/> will be ignored
        /// </summary>
        List<XmlElement> XmlElements { get; }
    }
}
